gamesite/chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.chat_rooms, name='chat_rooms'),
    path('<slug:slug>', views.chat_room, name='chat_room'),

]

gamesite/gamesite/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from api.views import NewsViewSet, GamesViewSet, CinemaViewSet, CommentNewsViewSet, CommentCinemaViewSet, CommentCinemaViewSet,\
CommentGamesViewSet, ProductsViewSet, CommentProductsViewSet, CustomerViewSet, OrderViewSet

router = routers.DefaultRouter()
router.register(r'news', NewsViewSet, basename='news')
router.register(r'games', GamesViewSet, basename='games')
router.register(r'cinema', CinemaViewSet, basename='cinema')
router.register(r'comment', CommentNewsViewSet, basename='comment_news')
router.register(r'comment-cinema', CommentCinemaViewSet, basename='Comment_cinema')
router.register(r'comment-games', CommentGamesViewSet, basename='Comment_games')
router.register(r'products', ProductsViewSet, basename='Products')
router.register(r'comment-products', CommentProductsViewSet, basename='Comment_products')
router.register(r'customer', CustomerViewSet, basename='customer')
router.register(r'order', OrderViewSet, basename='order')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('main.urls')),
    path('shop/', include('shop.urls')),
    path('forum/', include('forum.urls')),
    path('api/', include(router.urls)),
    # path('api/', include('api.urls')),
    path('api-auth/drf/', include('rest_framework.urls')),# systeme authentication here
    path(r'api-auth/', include('djoser.urls')),
    path(r'^auth/', include('djoser.urls.authtoken')),
    path('chat/', include('chat.urls')),
]

gamesite/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from main.views import HomeView, NewsDetailView, ContactView, NewsView, CinemaNewsView, GamesView, \
    GamesDetailView, CinemaDetailView, AboutView, AddComment, AddCommentCinema, AddCommentGames, SearchView, \
    AdminNewsCreateView, AdminNewsListView, AdminGamesCreateView, AdminGamesListView, AdminCinemaCreateView, \
    AdminCinemaListView, AdminDeleteNewsView, AdminDeleteCinemaView, AdminDeleteGamesView, AdminCinemaUpdateView, \
    AdminNewsUpdateView, AdminGamesUpdateView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('news/', NewsView.as_view(), name='news'),
    path('news/<str:slug>/', NewsDetailView.as_view(), name='news_detail'),
    path('comment-news/<int:pk>/', AddComment.as_view(), name='comment_news'),
    path('games/', GamesView.as_view(), name='games'),
    path('games/<str:slug>/', GamesDetailView.as_view(), name='games_detail'),
    path('comment-games-news/<int:pk>/', AddCommentGames.as_view(), name='comment_games_news'),
    path('cinema/', CinemaNewsView.as_view(), name='cinema'),
    path('cinema/<str:slug>/', CinemaDetailView.as_view(), name='cinema_detail'),
    path('comment-cinema-news/<int:pk>/', AddCommentCinema.as_view(), name='comment_cinema_news'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('about/', AboutView.as_view(), name='about'),
    path('search/', SearchView.as_view(), name='search'),
    #adminpages
    path('admin-news/add/', AdminNewsCreateView.as_view(), name='adminnewscreate'),
    path('admin-news/list/', AdminNewsListView.as_view(), name='adminnewslist'),
    path('admin-games/add/', AdminGamesCreateView.as_view(), name='admingamescreate'),
    path('admin-games/list/', AdminGamesListView.as_view(), name='admingameslist'),
    path('admin-cinema/add/', AdminCinemaCreateView.as_view(), name='admincinemacreate'),
    path('admin-cinema/list/', AdminCinemaListView.as_view(), name='admincinemalist'),
    path('delete-news/<str:slug>/', AdminDeleteNewsView.as_view(), name='delete_news'),
    path('update-news/<str:slug>/', AdminNewsUpdateView.as_view(), name='update_news'),
    path('delete-cinema/<str:slug>/', AdminDeleteCinemaView.as_view(), name='delete_cinema'),
    path('update-cinema/<str:slug>/', AdminCinemaUpdateView.as_view(), name='update_cinema'),
    path('delete-games/<str:slug>/', AdminDeleteGamesView.as_view(), name='delete_games'),
    path('update-games/<str:slug>/', AdminGamesUpdateView.as_view(), name='update_games'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gamesite/main/models.py
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.urls import reverse
from embed_video.fields import EmbedVideoField


class CategoryNews(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, null=True, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category', kwargs={'slug': self.slug})

    class Meta:
        ordering = ('name',)
        verbose_name = 'Category News'
        verbose_name_plural = 'Categories News'


class News(models.Model):
    title = models.CharField(max_length=250, verbose_name='News')
    slug = models.SlugField(max_length=200, db_index=True, null=True, unique=True)
    content = models.TextField(blank=True, verbose_name='Description')
    image = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name='Published')
    updated = models.DateTimeField(auto_now=True, verbose_name='Updated')
    available = models.BooleanField(default=True)
    category = models.ForeignKey(CategoryNews, on_delete=models.PROTECT, related_name='news',
                                 verbose_name='Category')

    class Meta:
        verbose_name = 'News'
        verbose_name_plural = 'News'
        ordering = ('-created',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('news_detail', kwargs={'slug': self.slug})

    def get_comment(self):
        return self.comment_set.filter(parent__isnull=True)


class NewsImage(models.Model):
    news = models.ForeignKey(News, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='photos/%Y/%m/%d/images/', blank=True)

    def __str__(self):
        return self.news.title


class Comment(models.Model):
    name = models.CharField(max_length=80)
    email = models.EmailField()
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    news = models.ForeignKey(News, on_delete=models.CASCADE, verbose_name='news')
    parent = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, verbose_name='parent')

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.news)

    class Meta:
        ordering = ('created',)


class CinemaNews(models.Model):
    title = models.CharField(max_length=250, verbose_name='Cinema_News')
    slug = models.SlugField(max_length=200, db_index=True, null=True, unique=True)
    content = models.TextField(blank=True, verbose_name='Description')
    image = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name='Published')
    updated = models.DateTimeField(auto_now=True, verbose_name='Updated')
    available = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Cinema News'
        verbose_name_plural = 'Cinema News'
        ordering = ('-created',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('cinema_detail', kwargs={'slug': self.slug})

    def get_comment(self):
        return self.comment_set.filter(parent__isnull=True)


class CinemaImage(models.Model):
    cinema_news = models.ForeignKey(CinemaNews, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='photos/%Y/%m/%d/images/', blank=True)

    def __str__(self):
        return self.cinema_news.title


class CinemaComment(models.Model):
    name = models.CharField(max_length=80)
    email = models.EmailField()
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    cinema = models.ForeignKey(CinemaNews, on_delete=models.CASCADE, verbose_name='news')
    parent = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, verbose_name='parent')

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.cinema)

    class Meta:
        ordering = ('created',)


class GamesCategory(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, null=True, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('games', kwargs={'slug': self.slug})

    class Meta:
        ordering = ('name',)
        verbose_name = 'Games Category'
        verbose_name_plural = 'Games Categories'


class Games(models.Model):
    title = models.CharField(max_length=250, verbose_name='Games')
    slug = models.SlugField(max_length=200, db_index=True, null=True, unique=True)
    content = models.TextField(blank=True, verbose_name='Description')
    image = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True)
    video = EmbedVideoField(null=True, blank=True, verbose_name='Video')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Published')
    updated = models.DateTimeField(auto_now=True, verbose_name='Updated')
    available = models.BooleanField(default=True)
    category = models.ForeignKey(GamesCategory, on_delete=models.PROTECT, related_name='games', null=True, blank=True,
                                 verbose_name='Game Category')

    class Meta:
        verbose_name = 'Game'
        verbose_name_plural = 'Games'
        ordering = ('-created',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('games_detail', kwargs={'slug': self.slug})


class GamesImage(models.Model):
    games_news = models.ForeignKey(Games, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='photos/%Y/%m/%d/images/', blank=True)

    def __str__(self):
        return self.games_news.title


class GamesComment(models.Model):
    name = models.CharField(max_length=80)
    email = models.EmailField()
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    games = models.ForeignKey(Games, on_delete=models.CASCADE, verbose_name='games_news')
    parent = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, verbose_name='parent')

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.games)

    class Meta:
        ordering = ('created',)

gamesite/main/forms.py
from django import forms

from main.models import Comment, CinemaComment, GamesComment, News, Games, CinemaNews


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'content')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'col-sm-12'}),
            'email': forms.TextInput(attrs={'class': 'col-sm-12'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 5}),
        }


class CinemaCommentForm(forms.ModelForm):
    class Meta:
        model = CinemaComment
        fields = ('name', 'email', 'content')


class GamesCommentForm(forms.ModelForm):
    class Meta:
        model = GamesComment
        fields = ('name', 'email', 'content')


class NewsForm(forms.ModelForm):
    more_images = forms.FileField(required=False, widget=forms.FileInput(attrs={
                'class': 'form-control',
                'multiple': True
            }))

    class Meta:
        model = News
        fields = ['title', 'slug', 'category', 'image', 'available', 'content']
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter the product title here...'
            }),
            'slug': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter the product slug here...'
            }),
            'category': forms.Select(attrs={
                'class': 'form-control'
            }),
            'image': forms.ClearableFileInput(attrs={
                'class': 'form-control'
            }),
            'available': forms.CheckboxInput(),
            'content': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Write description here',
                'rows': 5
            }),
        }


class GamesForm(forms.ModelForm):
    more_images = forms.FileField(required=False, widget=forms.FileInput(attrs={
                'class': 'form-control',
                'multiple': True
            }))

    class Meta:
        model = Games
        fields = ['title', 'slug', 'category', 'image', 'video', 'available', 'content']
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter the product title here...'
            }),
            'slug': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter the product slug here...'
            }),
            'category': forms.Select(attrs={
                'class': 'form-control'
            }),
            'image': forms.ClearableFileInput(attrs={
                'class': 'form-control'
            }),
            'available': forms.CheckboxInput(),
            'content': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Write description here',
                'rows': 5
            }),
            'video': forms.ClearableFileInput(attrs={
                'class': 'form-control'
            }),
        }


class CinemaForm(forms.ModelForm):
    more_images = forms.FileField(required=False, widget=forms.FileInput(attrs={
                'class': 'form-control',
                'multiple': True
            }))

    class Meta:
        model = CinemaNews
        fields = ['title', 'slug', 'image', 'available', 'content']
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter the product title here...'
            }),
            'slug': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter the product slug here...'
            }),
            'image': forms.ClearableFileInput(attrs={
                'class': 'form-control'
            }),
            'available': forms.CheckboxInput(),
            'content': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Write description here',
                'rows': 5
            }),
        }

gamesite/main/templates/main/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Contact us{% endblock title %}
{% block content %}
	<section class="page-section single-blog-page spad">
        <h3>About project </h3>
        <p>You can use this material and resources from out site.</p>
    </section>
{% endblock content %}

gamesite/main/templates/main/cinema_detail.html
{% extends 'base.html' %}
{% load static %}
{% load embed_video_tags %}
{% block title %}Cinema Detail{% endblock title %}
{% block content %}


<!-- Page info section -->
<section class="page-info-section set-bg" data-setbg="{% static 'img/page-top-bg/2.jpg' %}">
    <div class="pi-content">
        <div class="container">
            <div class="row">
                <div class="col-xl-5 col-lg-6 text-white">
                    <h2>{{ cinema.title|truncatewords:5 }}</h2>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Page info section -->


<!-- Page section -->
<section class="page-section single-blog-page spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="blog-thumb set-bg" data-setbg="{{ cinema.image.url }}">
                    <div class="cata new">{{ cinema.category }}</div>
                    <div class="rgi-extra">
                        <div class="rgi-star"><img src="{% static 'img/icons/star.png' %}" alt=""></div>
                        <div class="rgi-heart"><img src="{% static 'img/icons/heart.png' %}" alt=""></div>
                    </div>
                </div>
                <div class="blog-content">
                    <h3>{{ cinema.title }}</h3>
                    <a href="" class="meta-comment">3 comment</a>
                    <p>{{ cinema.content }}</p>
                    {% if cinema.video %}
                    <iframe width="560" height="315" src="{{ game.video }}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    {% endif %}
                </div>
                <div class="comment-warp">
						<h4 class="comment-title"><span>Total:{{ cinema.cinemacomment_set.count }}  </span>Comments</h4>
						<ul class="comment-list">
							{% for comment in cinema.cinemacomment_set.all %}
							<li>
								<div class="comment mt-4">
									<div class="comment-avator set-bg" data-setbg="{% static 'img/authors/1.jpg' %}"></div>
									<div class="comment-content">
										<h5>{{ comment.name }} <span>{{ comment.created }}</span></h5>
										<p>{{ comment.content }}</p>
										<a href="#formComment" class="reply" onclick="addComment('{{ comment.name }}', '{{ comment.id }}')">Reply</a>
									</div>
								</div>
								<div class="comment mt-5">
								{% for com in comment.comment_set.all %}
									<div class="comment-avator set-bg" data-setbg="{% static 'img/authors/1.jpg' %}"></div>
									<div class="comment-content">
										<h5>{{ com.name }} <span>{{ com.created }}</span></h5>
										<p>{{ com.content }}</p>
										<a href="#formComment" class="reply" onclick="addComment('{{ comment.name }}', '{{ comment.id }}')">Reply</a>
									</div>
								{% endfor %}
								</div>
							</li>
							{% endfor %}
						</ul>
					</div>
					<div class="comment-form-warp">
						<h4 class="comment-title">Leave Your Comment</h4>
						<form action="{% url 'comment_cinema_news' cinema.id %}" class="comment-form" method="post" id="formComment">
							{% csrf_token %}
							<input type="hidden" name="parent" id="contactparent" value="">
							<div class="row">
								<div class="col-md-6">
									<input class="form-control border" id="contactname" type="text" placeholder="Your name" name="name">
								</div>
								<div class="col-md-6">
									<input class="form-control border" id="contactemail" type="email" placeholder="Email" name="email">
								</div>
								<div class="col-lg-12">
									<textarea class="form-control border" id="contactcomment" rows="5" placeholder="Message" name="content"></textarea>
									<button class="site-btn btn-sm">Send</button>
								</div>
							</div>
						</form>
					</div>
				</div>
				<!-- sidebar -->
				<div class="col-lg-4 col-md-7 sidebar pt-5 pt-lg-0">
					<!-- widget -->
					<div class="widget-item">
						<form class="search-widget">
							<input type="text" placeholder="Search">
							<button><i class="fa fa-search"></i></button>
						</form>
					</div>
					<!-- widget -->
															<!-- widget -->
					<div class="widget-item">
						<h4 class="widget-title">Latest Comments</h4>
						<div class="latest-blog">
                            {% for comment in comments %}
							<div class="lb-item">
								<div class="lb-thumb set-bg" data-setbg="{% static 'img/latest-blog/1.jpg' %}"></div>
								<div class="lb-content">
									<div class="lb-date">{{ comment.created }}</div>
									<p>{{ comment.content|truncatewords:10 }}</p>
									<a href="#" class="lb-author">By {{ comment.name }}</a>
								</div>
							</div>
                            {% endfor %}
						</div>
					</div>
					<!-- widget -->
					<!-- widget -->
				</div>
			</div>
		</div>
	</section>
	<!-- Page section end -->
<script>
	function addComment(name, id) {
            document.getElementById("contactparent").value = id;
            document.getElementById("contactcomment").innerText = `${name}, `
        }
</script>
{% endblock content %}

gamesite/main/templates/main/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Contact us{% endblock title %}
{% block content %}


	<section class="page-section single-blog-page spad">
        <h3>Contact with us</h3>
        <h3><a href="https://www.linkedin.com/in/nickpashkevich/">LinkedIn</a> </h3>
        <h3><a href="https://github.com/Nicolai94">GitHUB</a></h3>
    </section>
{% endblock content %}

gamesite/main/templates/main/games_detail.html
{% extends 'base.html' %}
{% load static %}
{% load embed_video_tags %}
{% block title %}Games Detail{% endblock title %}
{% block content %}


<!-- Page info section -->
<section class="page-info-section set-bg" data-setbg="{% static 'img/page-top-bg/2.jpg' %}">
    <div class="pi-content">
        <div class="container">
            <div class="row">
                <div class="col-xl-5 col-lg-6 text-white">
                    <h2>{{ games.title|truncatewords:5 }}</h2>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Page info section -->


<!-- Page section -->
<section class="page-section single-blog-page spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="blog-thumb set-bg" data-setbg="{{ game.image.url }}">
                    <div class="cata new">{{ game.category }}</div>
                    <div class="rgi-extra">
                        <div class="rgi-star"><img src="{% static 'img/icons/star.png' %}" alt=""></div>
                        <div class="rgi-heart"><img src="{% static 'img/icons/heart.png' %}" alt=""></div>
                    </div>
                </div>
                <div class="blog-content">
                    <h3>{{ game.title }}</h3>
                    <a href="" class="meta-comment"><span>Total:{{ game.gamescomment_set.count }}</span> comment</a>
                    <p>{{ game.content }}</p>
                    {% if game.video %}
                    <iframe width="560" height="315" src="{{ game.video }}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    {% endif %}
                </div>
                <div class="comment-warp">
						<h4 class="comment-title"><span>Total:{{ game.gamescomment_set.count }}  </span>Comments</h4>
						<ul class="comment-list">
							{% for comment in games.gamescomment_set.all %}
							<li>
								<div class="comment mt-4">
									<div class="comment-avator set-bg" data-setbg="{% static 'img/authors/1.jpg' %}"></div>
									<div class="comment-content">
										<h5>{{ comment.name }} <span>{{ comment.created }}</span></h5>
										<p>{{ comment.content }}</p>
										<a href="#formComment" class="reply" onclick="addComment('{{ comment.name }}', '{{ comment.id }}')">Reply</a>
									</div>
								</div>
								<div class="comment mt-5">
								{% for com in gamescomment.comment_set.all %}
									<div class="comment-avator set-bg" data-setbg="{% static 'img/authors/1.jpg' %}"></div>
									<div class="comment-content">
										<h5>{{ com.name }} <span>{{ com.created }}</span></h5>
										<p>{{ com.content }}</p>
										<a href="#formComment" class="reply" onclick="addComment('{{ comment.name }}', '{{ comment.id }}')">Reply</a>
									</div>
								{% endfor %}
								</div>
							</li>
							{% endfor %}
						</ul>
					</div>
					<div class="comment-form-warp">
						<h4 class="comment-title">Leave Your Comment</h4>
						<form action="{% url 'comment_games_news' games.id %}" class="comment-form" method="post" id="formComment">
							{% csrf_token %}
							<input type="hidden" name="parent" id="contactparent" value="">
							<div class="row">
								<div class="col-md-6">
									<input class="form-control border" id="contactname" type="text" placeholder="Your name" name="name">
								</div>
								<div class="col-md-6">
									<input class="form-control border" id="contactemail" type="email" placeholder="Email" name="email">
								</div>
								<div class="col-lg-12">
									<textarea class="form-control border" id="contactcomment" rows="5" placeholder="Message" name="content"></textarea>
									<button class="site-btn btn-sm">Send</button>
								</div>
							</div>
						</form>
					</div>
				</div>
				<!-- sidebar -->
				<div class="col-lg-4 col-md-7 sidebar pt-5 pt-lg-0">
					<!-- widget -->
					<div class="widget-item">
						<form class="search-widget">
							<input type="text" placeholder="Search">
							<button><i class="fa fa-search"></i></button>
						</form>
					</div>
										<!-- widget -->
					<div class="widget-item">
						<h4 class="widget-title">Latest Comments</h4>
						<div class="latest-blog">
                            {% for comment in comments %}
							<div class="lb-item">
								<div class="lb-thumb set-bg" data-setbg="{% static 'img/latest-blog/1.jpg' %}"></div>
								<div class="lb-content">
									<div class="lb-date">{{ comment.created }}</div>
									<p>{{ comment.content|truncatewords:10 }}</p>
									<a href="#" class="lb-author">By {{ comment.name }}</a>
								</div>
							</div>
                            {% endfor %}
						</div>
					</div>
					<!-- widget -->
				</div>
			</div>
		</div>
	</section>
	<!-- Page section end -->
<script>
	function addComment(name, id) {
            document.getElementById("contactparent").value = id;
            document.getElementById("contactcomment").innerText = `${name}, `
        }
</script>
{% endblock content %}

gamesite/main/templates/main/games_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Games Page{% endblock title %}

{% block content %}

<!-- Page info section -->
<section class="page-info-section set-bg" data-setbg="{% static 'img/page-top-bg/3.jpg' %}">
	<div class="pi-content">
		<div class="container">
			<div class="row">
				<div class="col-xl-5 col-lg-6 text-white">
					<h2>Game reviews</h2>
					<p>This page with game review</p>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- Page info section -->


<!-- Page section -->
<section class="page-section review-page spad">
	<div class="container">
		<div class="row">
			{% for game in games %}
			<div class="col-lg-3 col-md-6">
				<div class="review-item">
					<div  class="review-cover set-bg" data-setbg="{{ game.image.url }} ">
						<div class="score yellow">9.3</div>
					</div>
					<div class="review-text">
						<h4><a href="{% url 'games_detail' game.slug %}">{{ game.title }}</a> </h4>
						<p>{{ game.content|truncatewords:10}}</p>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
		{% include 'inc/pagination.html' %}
	</div>
</section>
<!-- Page section end -->


<!-- Review section -->
<section class="review-section review-dark spad set-bg" data-setbg="{% static 'img/review-bg-2.jpg' %}">
	<div class="container">
		<div class="section-title text-white">
			<div class="cata new">new</div>
			<h2>Recent Reviews</h2>
		</div>
		<div class="row text-white">
			{% for product in all_products %}
			<div class="col-lg-3 col-md-6">
				<div class="review-item">
					<div class="review-cover set-bg" data-setbg="{{ product.image.url }}">
						<div class="score yellow">{{ product.category }}</div>
					</div>
					<div class="review-text">
						<h5><a href="{% url 'games_detail' product.slug %}">{{ product.title }}</a> </h5>
						<p>{{ product.description|truncatewords:5 }}</p>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
</section>
<!-- Review section end -->

{% endblock content %}

gamesite/main/templates/main/search.html
{% extends 'base.html' %}
{% block title %}Search page{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3>Search Results for <span class="text-info">"{{ request.GET.keyword }}"</span></h3>
                <hr>
                {% for result in results %}
                <div class="row">
                    <div class="col-md-4">
                        <img src="{{ result.image.url }}" alt="" class="img-fluid">
                    </div>
                    <div class="col-md-8">
                        <h4><a href="{% url 'news_detail' result.slug %}">{{ result.title }}</a></h4>
                        <p>{{ result.description|truncatewords:20 }}</p>
                    </div>
                </div>
                {% endfor %}
                </div>

            </div>
        </div>
    </div>
{% endblock content %}