gamesite/chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.chat_rooms, name='chat_rooms'),
    path('<slug:slug>', views.chat_room, name='chat_room'),

]

gamesite/gamesite/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from api.views import NewsViewSet, GamesViewSet, CinemaViewSet, CommentNewsViewSet, CommentCinemaViewSet, CommentCinemaViewSet,\
CommentGamesViewSet, ProductsViewSet, CommentProductsViewSet, CustomerViewSet, OrderViewSet

router = routers.DefaultRouter()
router.register(r'news', NewsViewSet, basename='news')
router.register(r'games', GamesViewSet, basename='games')
router.register(r'cinema', CinemaViewSet, basename='cinema')
router.register(r'comment', CommentNewsViewSet, basename='comment_news')
router.register(r'comment-cinema', CommentCinemaViewSet, basename='Comment_cinema')
router.register(r'comment-games', CommentGamesViewSet, basename='Comment_games')
router.register(r'products', ProductsViewSet, basename='Products')
router.register(r'comment-products', CommentProductsViewSet, basename='Comment_products')
router.register(r'customer', CustomerViewSet, basename='customer')
router.register(r'order', OrderViewSet, basename='order')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('main.urls')),
    path('shop/', include('shop.urls')),
    path('forum/', include('forum.urls')),
    path('api/', include(router.urls)),
    # path('api/', include('api.urls')),
    path('api-auth/drf/', include('rest_framework.urls')),# systeme authentication here
    path(r'api-auth/', include('djoser.urls')),
    path(r'^auth/', include('djoser.urls.authtoken')),
    path('chat/', include('chat.urls')),
]

gamesite/shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from shop.views import HomeView, ProductDetailView, CustomLoginView, RegisterView, CustomLogoutView, \
    CustomProfileView, AddToCartView, MyCartView, CheckoutView, ManageCartView, EmptyCartView, AddCommentProduct, \
    PasswordForgotView, PasswordResetView, CustomOrderDetailView, AdminLoginView, AdminHomeView, AdminOrderDetailView, \
    AdminOrderListView, AdminOrderStatusChangeView, AdminProductListView, AdminProductCreateView, \
    AdminProductDeleteView, AdminProductUpdateView


urlpatterns = [
    path('', HomeView.as_view(), name='shop_home'),
    path('/<str:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', CustomProfileView.as_view(), name='profile'),
    path('profile/order<int:pk>/', CustomOrderDetailView.as_view(), name='orderdetail'),
    path('add-to-cart-<int:pro_id>/', AddToCartView.as_view(), name='add_to_cart'),
    path('my-cart/', MyCartView.as_view(), name='mycart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('manage-carts/<int:cp_id>/', ManageCartView.as_view(), name='managecart'),
    path('empty-cart/', EmptyCartView.as_view(), name='emptycart'),
    path('comment-product/<int:pk>/', AddCommentProduct.as_view(), name='comment_product'),
    path('forgot-password/', PasswordForgotView.as_view(), name='passwordforgot'),
    path('/password-reset/<email>/<token>/', PasswordResetView.as_view(), name='passwordreset'),
    #admin pages
    path('admin-login/', AdminLoginView.as_view(), name='adminlogin'),
    path('admin-home/', AdminHomeView.as_view(), name='adminhome'),
    path('admin-order/<int:pk>/', AdminOrderDetailView.as_view(), name='adminorderdetail'),
    path('admin-order/<int:pk>/', AdminOrderDetailView.as_view(), name='adminorderdetail'),
    path('admin-all-orders/', AdminOrderListView.as_view(), name='adminorderlist'),
    path('admin-order-<int:pk>-change/', AdminOrderStatusChangeView.as_view(), name='adminorderstatuschange'),
    path('admin-product/list/', AdminProductListView.as_view(), name='adminproductlist'),
    path('admin-product/add/', AdminProductCreateView.as_view(), name='adminproductcreate'),
    path('delete-product/<str:slug>/', AdminProductDeleteView.as_view(), name='delete_products'),
    path('update-product/<str:slug>/', AdminProductUpdateView.as_view(), name='update_products'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gamesite/shop/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from embed_video.fields import EmbedVideoField


class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='admins')
    mobile = models.CharField(max_length=20)

    def __str__(self):
        return self.user.username


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name


class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('shop_home', kwargs={'slug': self.slug})


class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True)
    price = models.PositiveIntegerField()
    video = EmbedVideoField(null=True, blank=True, verbose_name='Video')
    description = models.TextField()
    minimal_requirements = models.TextField(null=True, blank=True)
    normal_requirements = models.TextField(null=True, blank=True)
    view_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'slug': self.slug})


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/images/')

    def __str__(self):
        return self.product.title


class ProductComment(models.Model):
    name = models.CharField(max_length=80)
    email = models.EmailField()
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    products = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='news')
    parent = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, verbose_name='parent')

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.products)

    class Meta:
        ordering = ('created',)


class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'Cart: ' + str(self.id)


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return 'Cart: ' + str(self.cart.id) + 'CartProduct:' + str(self.id)


ORDER_STATUS = (
    ('Order Received', 'Order Received'),
    ('Order Processing', 'Order Processing'),
    ('On the way', 'On the way'),
    ('Order Completed', 'Order Completed'),
    ('Order Canceled', 'Order Canceled'),

)


class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'Order: ' + str(self.id)

gamesite/shop/forms.py
from django import forms
from .models import *


class RegisterForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Customer
        fields = ['username', 'password', 'email', 'full_name', 'address']
        widgets = {
            'full_name': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
        }

        def clean_username(self):
            uname = self.cleaned_data.get('username')
            if User.objects.filter(username=uname).exists():
                raise forms.ValidationError(
                    'User with this username already exists.'
                )
            return uname


class CustomLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class CheckoutForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['ordered_by', 'shipping_address', 'mobile', 'email']


class ProductCommentForm(forms.ModelForm):
    class Meta:
        model = ProductComment
        fields = ('name', 'email', 'content')


class PasswordForgotForm(forms.Form):
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter the email used in customer account',
    }))

    def clean_email(self):
        e = self.cleaned_data.get('email')
        if Customer.objects.filter(user__email=e).exists():
            pass
        else:
            raise forms.ValidationError('Customer with this account does not exists ..')
        return e


class PasswordResetForm(forms.Form):
    new_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'autocomplete': 'new-password',
        'placeholder': 'Enter New Password'
    }), label='New Password')
    confirm_new_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'autocomplete': 'new-password',
        'placeholder': 'Confirm New Password'
    }), label='Confirm New Password')

    def clean_confirm_new_password(self):
        new_password = self.cleaned_data.get('new_password')
        confirm_new_password = self.cleaned_data.get('confirm_new_password')
        if new_password != confirm_new_password:
            raise forms.ValidationError(
                'New passwords did not match!'
            )
        return confirm_new_password


class ProductForm(forms.ModelForm):
    more_images = forms.FileField(required=False, widget=forms.FileInput(attrs={
                'class': 'form-control',
                'multiple': True
            }))

    class Meta:
        model = Product
        fields = ['title', 'slug', 'category', 'image', 'price', 'description', 'minimal_requirements',
                  'normal_requirements', 'video']
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter the product title here...'
            }),
            'slug': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter the product slug here...'
            }),
            'category': forms.Select(attrs={
                'class': 'form-control'
            }),
            'image': forms.ClearableFileInput(attrs={
                'class': 'form-control',
                'multiple': True
            }),
            'price': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Price of the product'
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Write description here',
                'rows': 5
            }),
            'minimal_requirements': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Minimal requirements',
                'rows': 5
            }),
            'normal_requirements': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Normal requirements',
                'rows': 5
            }),
            'video': forms.ClearableFileInput(attrs={
                'class': 'form-control',
            }),
        }

gamesite/shop/templates/shop/add_to_cart.html
{% extends 'base.html' %}
{% block title %}Add to cart{% endblock %}
{% block content %}
<div class="container">
  <h3>Product added to cart success)))</h3>
</div>
{% endblock %}

gamesite/shop/templates/shop/checkout.html
{% extends 'base.html' %}
{% block title %}Checkout{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3>Items in the cart</h3>
            <a href="{% url 'mycart' %}">Update Cart</a>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total</th>
                        <th>$ {{ cart.total }}</th>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-6">
            <h3>Checkout form</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-info">Place order</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

gamesite/shop/templates/shop/mycart.html
{% extends 'base.html' %}
{% block title %}My Cart{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h4>Items in my cart</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                        <td>
                            <a href="{% url 'managecart' cp.id %}?action=inc" class="btn btn-primary">+</a>
                            <a href="{% url 'managecart' cp.id %}?action=dcr" class="btn btn-warning">-</a>
                            <a href="{% url 'managecart' cp.id %}?action=rmv" class="btn btn-danger">x</a>
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total</th>
                        <th>$ {{ cart.total }}</th>
                        {% if cart.cartproduct_set.all %}
                        <th><a href="{% url 'emptycart' %}">Empty Cart</a> </th>
                        {% endif %}
                    </tr>
                    {% if cart.cartproduct_set.all %}
                    <tr>
                        <th><a class="btn btn-info" href="{% url 'checkout' %}">Checkout</a> </th>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

gamesite/shop/templates/shop/orderdetail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block title %}Order Detail{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <h3>Order Detail</h3>
            <p><span style="font-weight-bold">Order ID:</span>#ORDER_{{ ord_obj.id }}</p>
            <p><span style="font-weight-bold">Order Status:</span>{{ ord_obj.order_status  }}</p>
            <p><span style="font-weight-bold">Order on:</span>{{ ord_obj.created_at }}{{ ord_obj.created_at|timesince }} ago</p>
            <p><span style="font-weight-bold">Shipping Information:</span>By {{ ord_obj.ordered_by }}.{{ ord_obj.mobile }}</p>
            <p><span style="font-weight-bold">Shipping Address:</span>By {{ ord_obj.shipping_address }}{{ ord_obj.email }}</p>
            <h4>Ordered Items</h4>
            <table>
                <thead>
                    <th>SN</th>
                    <th>Item</th>
                    <th>Rate</th>
                    <th>Quantity</th>
                    <th>Subtotal</th>
                </thead>
                <tbody>
                    {% for cp in ord_obj.cart.cartproduct_set.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><a target="_blank" href="{% url 'product_detail' cp.product.slug %}">{{ cp.product.title }}({{ cp.product.id }})</a></td>
                        <td>{{ cp.rate }}</td>
                        <td>{{ cp.quantity }}</td>
                        <td>{{ cp.subtotal }}</td>
                    </tr>
                    {% endfor %}
                <tr>
                    <th colspan="4" class="text-right">Total:</th>
                    <th>$ {{ ord_obj.total|intcomma }}/</th>
                </tr>
                </tbody>
            </table>



        </div>
    </div>
</div>
{% endblock %}

gamesite/shop/templates/shop/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% load embed_video_tags %}
{% block title %}Product Detail{% endblock title %}
{% block content %}

<!-- Latest news section -->
<div class="latest-news-section">
    <div class="ln-title">Latest News</div>
    <div class="news-ticker">
        <div class="news-ticker-contant">
            <div class="nt-item"><span class="new">new</span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. </div>
            <div class="nt-item"><span class="strategy">strategy</span>Isum dolor sit amet, consectetur adipiscing elit. </div>
            <div class="nt-item"><span class="racing">racing</span>Isum dolor sit amet, consectetur adipiscing elit. </div>
        </div>
    </div>
</div>
<!-- Latest news section end -->


<!-- Page info section -->
<section class="page-info-section set-bg" data-setbg="{% static 'img/page-top-bg/2.jpg' %}">
    <div class="pi-content">
        <div class="container">
            <div class="row">
                <div class="col-xl-5 col-lg-6 text-white">
                    <h2>{{ product.title|truncatewords:5 }}</h2>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Page info section -->


<!-- Page section -->
<section class="page-section single-blog-page spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="blog-thumb set-bg" data-setbg="{{ product.image.url }}">
                    <div class="cata new">{{ product.category}}</div>
                    <div class="cata new">Price: ${{ product.price }}</div>
                    <div class="cata new">Viewed {{ product.view_count }} times</div>
                </div>
                <div class="blog-content">
                    <h3>{{ product.title }} </h3>
                    <a href="{% url 'add_to_cart' product.id %}" class="btn btn-info">Add to card</a>
                    <a href="" class="meta-comment">3 comment</a>
                    <p>{{ product.description }}</p><br>
                    <p>{{ product.minimal_requirements }}</p><br>
                    <p>{{ product.normal_requirements }}</p>
                    <div class="row">
                        {% for p in product.productimage_set.all %}
                            <div class="col-md-4">
                                <img src="{{ p.image.url }}" class="img-fluid" style="height: 100px; object-fit: contain;">
                            </div>
                        {% endfor %}
                    </div>
                    {% if product.video %}
                    <iframe width="560" height="315" src="{{ product.video }}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    {% endif %}
                </div>
                <div class="comment-warp">
						<h4 class="comment-title"><span>Total:{{ product.productcomment_set.count }}  </span>Comments</h4>
						<ul class="comment-list">
							{% for comment in product.productcomment_set.all %}
							<li>
								<div class="comment mt-4">
									<div class="comment-avator set-bg" data-setbg="{% static 'img/authors/1.jpg' %}"></div>
									<div class="comment-content">
										<h5>{{ comment.name }} <span>{{ comment.created }}</span></h5>
										<p>{{ comment.content }}</p>
										<a href="#formComment" class="reply" onclick="addComment('{{ comment.name }}', '{{ comment.id }}')">Reply</a>
									</div>
								</div>
								<div class="comment mt-5">
								{% for com in productcomment.comment_set.all %}
									<div class="comment-avator set-bg" data-setbg="{% static 'img/authors/1.jpg' %}"></div>
									<div class="comment-content">
										<h5>{{ com.name }} <span>{{ com.created }}</span></h5>
										<p>{{ com.content }}</p>
										<a href="#formComment" class="reply" onclick="addComment('{{ comment.name }}', '{{ comment.id }}')">Reply</a>
									</div>
								{% endfor %}
								</div>
							</li>
							{% endfor %}
						</ul>
					</div>
					<div class="comment-form-warp">
						<h4 class="comment-title">Leave Your Comment</h4>
						<form action="{% url 'comment_product' product.id %}" class="comment-form" method="post" id="formComment">
							{% csrf_token %}
							<input type="hidden" name="parent" id="contactparent" value="">
							<div class="row">
								<div class="col-md-6">
									<input class="form-control border" id="contactname" type="text" placeholder="Your name" name="name">
								</div>
								<div class="col-md-6">
									<input class="form-control border" id="contactemail" type="email" placeholder="Email" name="email">
								</div>
								<div class="col-lg-12">
									<textarea class="form-control border" id="contactcomment" rows="5" placeholder="Message" name="content"></textarea>
									<button class="site-btn btn-sm">Send</button>
								</div>
							</div>
						</form>
					</div>
            </div>
            <!-- sidebar -->
            <div class="col-lg-4 col-md-7 sidebar pt-5 pt-lg-0">
                <!-- widget -->
                <div class="widget-item">
                    <form class="search-widget">
                        <input type="text" placeholder="Search">
                        <button><i class="fa fa-search"></i></button>
                    </form>
                </div>
                <!-- widget -->
                <div class="widget-item">
                    <h4 class="widget-title">Latest Posts</h4>
                    <div class="latest-blog">
                        <div class="lb-item">
                            <div class="lb-thumb set-bg" data-setbg="img/latest-blog/1.jpg"></div>
                            <div class="lb-content">
                                <div class="lb-date">June 21, 2018</div>
                                <p>Ipsum dolor sit amet, consectetur adipisc ing consecips</p>
                                <a href="#" class="lb-author">By Admin</a>
                            </div>
                        </div>
                        <div class="lb-item">
                            <div class="lb-thumb set-bg" data-setbg="img/latest-blog/2.jpg"></div>
                            <div class="lb-content">
                                <div class="lb-date">June 21, 2018</div>
                                <p>Ipsum dolor sit amet, consectetur adipisc ing consecips</p>
                                <a href="#" class="lb-author">By Admin</a>
                            </div>
                        </div>
                        <div class="lb-item">
                            <div class="lb-thumb set-bg" data-setbg="img/latest-blog/3.jpg"></div>
                            <div class="lb-content">
                                <div class="lb-date">June 21, 2018</div>
                                <p>Ipsum dolor sit amet, consectetur adipisc ing consecips</p>
                                <a href="#" class="lb-author">By Admin</a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- widget -->
                <div class="widget-item">
                    <h4 class="widget-title">Tags</h4>
                    <div class="top-comment">
                        <div class="tc-item">
                            <div class="tc-thumb set-bg" data-setbg="img/authors/1.jpg"></div>
                            <div class="tc-content">
                                <p><a href="#">James Smith</a> <span>on</span> Lorem consec ipsum dolor sit amet, co</p>
                                <div class="tc-date">June 21, 2018</div>
                            </div>
                        </div>
                        <div class="tc-item">
                            <div class="tc-thumb set-bg" data-setbg="img/authors/2.jpg"></div>
                            <div class="tc-content">
                                <p><a href="#">Michael James</a> <span>on</span>Cras sit amet sapien aliquam</p>
                                <div class="tc-date">June 21, 2018</div>
                            </div>
                        </div>
                        <div class="tc-item">
                            <div class="tc-thumb set-bg" data-setbg="img/authors/3.jpg"></div>
                            <div class="tc-content">
                                <p><a href="#">Justin More</a> <span>on</span> Lorem ipsum dolor consecsit amet, co</p>
                                <div class="tc-date">June 21, 2018</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Page section end -->

{% endblock %}

gamesite/shop/templates/shop/shop_home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Shop Home Page{% endblock title %}
{% block content %}


<!--&lt;!&ndash; Feature section &ndash;&gt;-->
<!--<section class="feature-section spad">-->
<!--    <div class="container">-->
<!--        <div class="row">-->
<!--            {% for product in product_list %}-->
<!--            <div class="col-lg-3 col-md-6 p-0">-->
<!--                <div class="feature-item set-bg" data-setbg="{{ product.image.url }}">-->
<!--                    <span class="cata new">{{ product.category }}</span>-->
<!--                    <div class="fi-content text-white">-->
<!--                        <h5><a href="#">{{ product.title }}</a></h5>-->
<!--                        <p>{{ product.content|truncatewords:8 }}</p>-->
<!--                        <a href="#" class="fi-comment">3 Comments</a><p class="fi-comment">{{ product.created }}</p>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--            {% endfor %}-->
<!--        </div>-->
<!--    </div>-->
<!--</section>-->
<!--&lt;!&ndash; Feature section end &ndash;&gt;-->


<!-- Review section -->
<section class="review-section spad set-bg" data-setbg="{% static 'img/review-bg.png' %}">
    <div class="container">
        <div class="section-title">
            <div class="cata new">new</div>
            <h2>Recent Shop Games</h2>
        </div>
        <div class="row">
            {% for product in product_list %}
            <div class="col-lg-3 col-md-6">
                <div class="review-item">
                    <div class="review-cover set-bg" data-setbg="{{ product.image.url }}">
                        <div class="score yellow">{{ product.category }}</div>
                    </div>
                    <div class="review-text">
                        <h5><a href="{% url 'product_detail' product.slug %}">{{ product.title }}</a></h5>
                        <p>{{ product.description|truncatewords:7 }}</p><br>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="site-pagination">
            <nav aria-label="...">
            <ul class="pagination">
                {% if product_list.has_previous %}
                <li class="page-item">
                  <a class="page-link" href="?page={{ product_list.previous_page_number }}">Previous</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                  <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                </li>
                {% endif %}
                {% for i in product_list.paginator.page_range %}
                {% if i == product_list.number %}
                <li class="page-item active"><a class="page-link">{{ i }}</a></li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
                {% endfor %}
                {% if product_list.has_next %}
                <li class="page-item">
                  <a class="page-link" href="?page={{ product_list.next_page_number }}">Next</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                  <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
                </li>
                {% endif %}
            </ul>
        </nav>
        </div>
    </div>
</section>
<!-- Review section end -->


{% endblock content %}